version: '2'

services:
  backend-1:
    image: cassandra:3.11.13
    networks:
      - backend
    ports:
      - 9044:9042
    mem_limit: 2G
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=backend-1
      - CASSANDRA_CLUSTER_NAME=c3-cluster
#  backend-2:
#    image: cassandra:3.11.13
#    networks:
#      - backend
#    mem_limit: 2G
#    cap_add:
#      - IPC_LOCK
#    ulimits:
#      memlock: -1
#    depends_on:
#      - backend-1
#    environment:
#      - HEAP_NEWSIZE=128M
#      - MAX_HEAP_SIZE=1024M
#      - CASSANDRA_SEEDS=backend-1
#      - CASSANDRA_CLUSTER_NAME=c3-cluster
#  backend-3:
#    image: cassandra:3.11.13
#    networks:
#      - backend
#    mem_limit: 2G
#    cap_add:
#      - IPC_LOCK
#    ulimits:
#      memlock: -1
#    depends_on:
#      - backend-2
#    environment:
#      - HEAP_NEWSIZE=128M
#      - MAX_HEAP_SIZE=1024M
#      - CASSANDRA_SEEDS=backend-1
#      - CASSANDRA_CLUSTER_NAME=c3-cluster
  stargate:
    image: stargateio/stargate-3_11:v1.0.77
    depends_on: 
      - backend-1
    networks:
      - backend
    ports:
      # cql
      - 9045:9042
      # graphql
      - 8080:8080
      # auth
      - 8081:8081
      # REST
      - 8082:8082
      # health
      - 8084:8084
      # grpc
      - 8090:8090
    mem_limit: 2G
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=c3-cluster
      - CLUSTER_VERSION=3.11
      - SEED=backend-1
      - RACK_NAME=rack1
      - DATACENTER_NAME=datacenter1
      - ENABLE_AUTH=true
networks:
  backend:
